#!/bin/bash

echo "=========================================="
echo "🚀 SUBIR PROYECTO A GITHUB"
echo "=========================================="
echo ""
echo "Repositorio: https://github.com/gerencianovapasion-code/pasionsame"
echo ""
echo "Opciones:"
echo ""
echo "1. USANDO GITHUB CLI (Recomendado):"
echo "   gh auth login"
echo "   gh repo create gerencianovapasion-code/pasionsame --public --source=. --remote=origin --push"
echo ""
echo "2. USANDO GIT CON TOKEN:"
echo "   git push -u origin main"
echo "   Username: gerencianovapasion-code"
echo "   Password: [Tu Personal Access Token]"
echo ""
echo "3. DESCARGAR Y USAR GITHUB DESKTOP:"
echo "   https://desktop.github.com/"
echo ""
echo "=========================================="
echo "CREAR TOKEN DE ACCESO:"
echo "=========================================="
echo "1. Ir a: https://github.com/settings/tokens/new"
echo "2. Note: PasionSame Deployment"
echo "3. Expiration: No expiration"
echo "4. Select scopes: repo (marcar todo)"
echo "5. Generate token"
echo "6. Copiar el token (empieza con ghp_...)"
echo "7. Usar como password al hacer push"
echo ""
